### ISSUE TITLE
Timestamp format of the camera

### ISSUE THREAD

**Issue by dcazzato** [alliedvision/VmbPy#37]
Dear all,

I am comparing the `frame.get_timestamp()` function return value with the system time `time.time()` since I am getting very different results.

For example, printing both outputs I obtain the following: 

```
Acquired Frame(id=98, status=FrameStatus.Complete, buffer=0x29d6247c040) at time 13905354715900 # frame.get_timestamp()
Acquired Frame(id=98, status=FrameStatus.Complete, buffer=0x29d6247c040) at time 1729090310.3095067 # sys time
```

Can I receive more information on the format?
Best,

**Comment by Teresa-AlliedVision** [comment]
Hi, for Alvium cameras the timestamp is nanoseconds since boot unless you use the TimestampReset feature to set it to 0. The frame timestamp is the camera timestamp at the start of the exposure.
Since this case it not related to the Python API, any follow up questions need to go through the support contact form on our website.
https://www.alliedvision.com/en/about-us/contact-us/technical-support-repair-/-rma/
